# Nome da aplicação
spring.application.name=API-Base

# Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_Library_Light?socketTimeout=60
spring.datasource.username=x
spring.datasource.password=xa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=60000

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Porta do servidor
server.port=8080
