CREATE TABLE public."Library" (
    "ID_Library" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Location" text NOT NULL
);

CREATE TABLE public."Author" (
    "ID_Author" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Age" integer NOT NULL,
    "Biography" text NOT NULL
);

CREATE TABLE public."Book" (
    "ID_Book" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ISBN" text NOT NULL,
    "Title" text NOT NULL,
    "Sinopse" text NOT NULL
);

CREATE TABLE public."Clients" (
    "ID_Clients" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL,
    "Adress" text NOT NULL
);

CREATE TABLE public."Book_Author" (
    "ID_Book" integer NOT NULL,
    "ID_Author" integer NOT NULL,
    PRIMARY KEY ("ID_Book", "ID_Author"),
    FOREIGN KEY ("ID_Author") REFERENCES public."Author"("ID_Author"),
    FOREIGN KEY ("ID_Book") REFERENCES public."Book"("ID_Book")
);

CREATE TABLE public."Stock" (
    "ID_Library" integer NOT NULL,
    "ID_Book" integer NOT NULL,
    "Qty" integer,
    PRIMARY KEY ("ID_Library", "ID_Book"),
    FOREIGN KEY ("ID_Book") REFERENCES public."Book"("ID_Book"),
    FOREIGN KEY ("ID_Library") REFERENCES public."Library"("ID_Library")
);

CREATE TABLE public."Reservations" (
    "ID_Reservation" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_Library" integer NOT NULL,
    "ID_Book" integer NOT NULL,
    "ID_Clients" integer NOT NULL,
    FOREIGN KEY ("ID_Book") REFERENCES public."Book"("ID_Book"),
    FOREIGN KEY ("ID_Clients") REFERENCES public."Clients"("ID_Clients"),
    FOREIGN KEY ("ID_Library") REFERENCES public."Library"("ID_Library")
);
