# Nome da aplicação
spring.application.name=API-Base

# Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_Library_Light?socketTimeout=60
spring.datasource.username=x
spring.datasource.password=xa
spring.datasource.driver-class-name=org.postgresql.Driver

# Mostrar as queries SQL no console
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=60000

spring.cache.ehcache.config=classpath:ehcache.xml
spring.main.allow-bean-definition-overriding=true


# Porta do servidor
server.port=8080
